import argparse
import xmltodict
import sys
import coding


def main():
    parser = argparse.ArgumentParser(description='Generate C++ header file from ARM SVD file.')
    parser.add_argument('svd_file', help="SVD file")
    parser.add_argument('-o', '--output', help="C++ header file name")
    args = parser.parse_args()
    svd_file = args.svd_file
    h_file = args.output
    print('/**')
    print(' * Generated by: {}'.format(' '.join(sys.argv)))
    print(' * Input file: {}'.format(svd_file))
    print(' * Output file: {}'.format(h_file))
    print(' */\n')
    print('#pragma once\n')
    print('#include <cstddef>\n')
    with open(svd_file) as file:
        doc = xmltodict.parse(file.read())
    coder = coding.Coder()
    coder.emit_mcu(doc['device'])


if __name__ == '__main__':
    main()
